service: dotnet-crud

provider:
  name: aws
  runtime: dotnetcore3.1
  lambdaHashingVersion: 20201221

package:
  individually: true

functions:
  get-transactions:
    handler: CsharpHandlers::TransactionsEventSourcing.Controller::GetTransactionsHandler

    package:
      artifact: bin/Release/netcoreapp3.1/hello.zip
